
#### general settings

name: 01_IRN+_DB_x4_scratch_DIV2K
use_tb_logger: true
model: IRN+
distortion: sr
scale: 4
gpu_ids: [2]


#### datasets

datasets:
  train:
    name: DIV2K
    mode: LQGT
    dataroot_GT: ~ # path to training HR images
    dataroot_LQ: ~ # path to training reference LR images, not necessary, if not provided, LR images will be generated in dataloader

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 16
    GT_size: 144
    use_flip: true
    use_rot: true
    color: RGB

  val:
    name: val_DIV2K
    mode: LQGT
    dataroot_GT: ~ # path to validation HR images
    dataroot_LQ: ~ # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader


#### network structures

network_G:
  which_model_G:
      subnet_type: DBNet
  in_nc: 3
  out_nc: 3
  block_num: [8, 8]
  scale: 4
  init: xavier

network_D:
  which_model_D: discriminator_vgg_128
  in_nc: 3
  nf: 64


#### path

path:
  pretrain_model_G: ../experiments/pretrained_models/IRN_x4.pth
  strict_load: true
  resume_state: ~


#### training settings: learning rate scheme, loss

train:
  lr_G: !!float 1e-4
  beta1: 0.9
  beta2: 0.999
  niter: 400000
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps: [50000, 100000, 200000, 300000]
  lr_gamma: 0.5

  pixel_criterion_forw: l2
  pixel_criterion_back: l1
  feature_criterion: l1
  feature_weight: 0.01

  manual_seed: 10

  val_freq: !!float 5e3

  lambda_fit_forw: 16
  lambda_rec_back: 0.01

  gradient_clipping: 10
  weight_decay_G: !!float 1e-5

  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  gan_type: gan
  gan_weight: !!float 1
  D_update_ratio: 1
  D_init_iters: 5000


#### logger

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
