
#### general settings

name: 01_IRN_DB_x2_scratch_DIV2K
use_tb_logger: true
model: IRN
distortion: sr
scale: 2
gpu_ids: [9]


#### datasets

datasets:
  train:
    name: DIV2K
    mode: LQGT
    # dataroot_GT: ~ # path to training HR images
    # dataroot_LQ: ~ # path to training reference LR images, not necessary, if not provided, LR images will be generated in dataloader
    dataroot_GT: "/disk1/ouyang/proj/invert_image_op/Invertible-Image-Rescaling/DIV2K/DIV2K_train_HR/" # path to training HR images
    dataroot_LQ: "/disk1/ouyang/proj/invert_image_op/Invertible-Image-Rescaling/DIV2K/DIV2K_train_LR_bicubic/X2/" # path to training reference LR images, not necessary, if not provided, LR images will be generated in dataloader

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 16
    GT_size: 144
    use_flip: true
    use_rot: true
    color: RGB

  val:
    name: val_DIV2K
    mode: LQGT
    # dataroot_GT: ~ # path to validation HR images
    # dataroot_LQ: ~ # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader
    dataroot_GT: "/disk1/ouyang/proj/invert_image_op/Invertible-Image-Rescaling/DIV2K/DIV2K_test_LR_bicubic/X2/" # path to training HR images
    dataroot_LQ: "/disk1/ouyang/proj/invert_image_op/Invertible-Image-Rescaling/DIV2K/DIV2K_test_LR_bicubic/X4/" # path to training reference LR images, not necessary, if not provided, LR images will be generated in dataloader


#### network structures

network_G:
  which_model_G:
      subnet_type: DBNet
  in_nc: 3
  out_nc: 3
  block_num: [8]
  scale: 2
  init: xavier


#### path

path:
  pretrain_model_G: ~ 
  strict_load: true
  resume_state: ~


#### training settings: learning rate scheme, loss

train:
  lr_G: !!float 2e-4
  beta1: 0.9
  beta2: 0.999
  niter: 500000
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps: [100000, 200000, 300000, 400000]
  lr_gamma: 0.5

  pixel_criterion_forw: l2
  pixel_criterion_back: l1

  manual_seed: 10

  val_freq: !!float 5e3

  lambda_fit_forw: 4.
  lambda_rec_back: 1
  lambda_ce_forw: 1
  weight_decay_G: !!float 1e-5
  gradient_clipping: 10


#### logger

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
